name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release "-p:Version=5.0.${{ github.run_number }}" "-p:PackageVersion=5.0.${{ github.run_number }}"
      - name: Test
        run: dotnet test --no-build --configuration Release MbCacheTest/MbCacheTest.csproj
      - name: Push to nuget.org
        run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
